from flask import request
from flask_restful import Resource

from glados.api.entity.serializers import EntitiesRequestSerializer, EntitiesTTSRequestSerializer, EntityResponseSerializer, EntityUpdateSerializer
from glados.repositories.entities import get_entities, update_entity_status, update_entity_value, get_all_rooms, get_entity_by_id, update_entity_general
from glados import constants
from marshmallow import ValidationError
import json
import os
import requests
from google.cloud import texttospeech
import base64


class EntitiesAPI(Resource):
	def get(self):
		request_serializer = EntitiesRequestSerializer()
		data = request_serializer.load(request.args)

		entities = get_entities(data)

		if not entities:
			return {"message": "No entities found", "data": []}, 200
		serializer = EntityResponseSerializer(many=True)
		return serializer.dump(entities), 200

	def patch(self):
		data = request.get_json()
		entity_id = data.get("id")
		new_status = data.get("status")
		new_value = data.get("value")
		if not entity_id or (new_status is None and new_value is None):
			return {"message": "Missing id or update fields"}, 400
		entity = None
		if new_status is not None:
			entity = update_entity_status(entity_id, new_status)
		if new_value is not None:
			entity = update_entity_value(entity_id, new_value)
		if not entity:
			return {"message": "Entity not found"}, 404
		serializer = EntityResponseSerializer()
		return serializer.dump(entity), 200


class TypesAPI(Resource):
	def get(self):
		types = [t.name for t in constants.EntityType]
		return {"types": types}, 200

class EntityAPI(Resource):
	def patch(self, entity_id):
		data = request.get_json()
		serializer = EntityUpdateSerializer()
		try:
			validated_data = serializer.load(data)
		except ValidationError as err:
			return {"errors": err.messages}, 422

		try:
			entity = update_entity_general(
				entity_id,
				name=validated_data.get("name"),
				type=validated_data.get("type"),
				room_id=validated_data.get("room_id"),
			)
			if not entity:
				raise Exception
		except Exception as e:
			return {"message": "Entity not found or update failed"}, 404

		response_serializer = EntityResponseSerializer()
		return response_serializer.dump(entity), 200

class EntitiesTTSAPI(Resource):
	def get(self):
		request_serializer = EntitiesTTSRequestSerializer()
		data = request_serializer.load(request.args)

		# Get language and voice from query params, default to English
		language = request.args.get("language", "en-US")
		voice_name = request.args.get("voice", None)  # e.g., 'en-US-Wavenet-F'

		entities = get_entities(data)
		if not entities:
			return {"message": "No entities found", "data": []}, 200

		serialized_entities = [
			{
				"name": entity.name,
				"status": entity.status,
				"value": entity.value
			}
			for entity in entities
		]

		# Improved prompt for Gemini, with language support
		prompt = (
			f"You are a smart home assistant. You work for a company named Neuralytics, so great them. Given the following list of entities (devices), each with a name, status, and optional value, "
			f"generate a concise, natural-sounding spoken summary of the current state of the home. "
			f"The summary should be suitable for being read aloud, and should be in the following language: {language}. "
			f"Group similar statuses, mention important values, and use a friendly, human tone. "
			f"Here is the list of entities: {json.dumps(serialized_entities)}. "
			f"Respond only with the summary sentence, no explanations."
			f"Finish by adding a sweat word depending on the time of the day and the weather."

		)
		GEMINI_API_KEY = os.getenv("GOOGLE_API_KEY")
		
		url = f"https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash:generateContent?key={GEMINI_API_KEY}"
		headers = {"Content-Type": "application/json"}
		payload = {
			"contents": [
				{"parts": [{"text": prompt}]}
			]
		}
		try:
			response = requests.post(url, headers=headers, json=payload, timeout=20)
			data = response.json()
			output = data.get("candidates", [{}])[0].get("content", {}).get("parts", [{}])[0].get("text")
			if not output:
				raise Exception(F"No summary generated by Gemini.{GEMINI_API_KEY}")
		except Exception as e:
			return {"error": f"Gemini API error: {str(e)}"}, 503

		# Use Google Cloud Text-to-Speech to synthesize the summary
		# output = "Bonjour !"
		try:
			tts_client = texttospeech.TextToSpeechClient()
			synthesis_input = texttospeech.SynthesisInput(text=output)
			# If a specific voice is requested, use it; otherwise, use language and neutral gender
			if voice_name:
				voice = texttospeech.VoiceSelectionParams(
					language_code=language,
					name=voice_name
				)
			else:
				voice = texttospeech.VoiceSelectionParams(
					language_code=language,
					name=f"{language}-Chirp3-HD-Achernar"
				)
			audio_config = texttospeech.AudioConfig(
				audio_encoding=texttospeech.AudioEncoding.MP3
			)
			tts_response = tts_client.synthesize_speech(
				input=synthesis_input,
				voice=voice,
				audio_config=audio_config
			)
			audio_base64 = base64.b64encode(tts_response.audio_content).decode("utf-8")
		except Exception as e:
			return {"error": f"TTS API error: {str(e)}"}, 500

		return {
			"summary": output,
			"audio_base64": audio_base64,
			"language": language,
			"voice": voice_name or "default"
		}, 200

